version: '3'
services:
  frontend:
    build:
      context: ./
    ports:
      - '3000:3000'
    container_name: fe
    depends_on:
      - backend
    volumes:
      - ./node_modules:/app/node_modules
  backend:
    build:
      context: ../DevSeries-Backend-Flask/
    ports:
      - '5001:5000'
    container_name: be
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../DevSeries-Backend-Flask/:/app
